// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Mvc02.Data;
using System;

namespace Mvc02.Migrations
{
    [DbContext(typeof(SubjectDb))]
    [Migration("20170919085143_SubjectAddInstructorName")]
    partial class SubjectAddInstructorName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mvc02.Models.Subject", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10);

                    b.Property<string>("CourseOutline");

                    b.Property<int>("Days");

                    b.Property<string>("Description");

                    b.Property<int>("Hours");

                    b.Property<string>("InstructorName");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Code");

                    b.ToTable("Subjects");
                });
#pragma warning restore 612, 618
        }
    }
}
